apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
  labels:
    tenant: a
    purpose: ci-runner
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b
  labels:
    tenant: b
    purpose: production
