apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edera-protect
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: edera-protect
  endpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - kube-system
